load("//tools:tar.bzl", "easy_tar")

easy_tar(
    name = "python3",
    srcs = [
        "//python3/mnt",
    ],
    out = "KoboRoot.tgz",
    strip_prefix = "python3",
    visibility = ["//visibility:public"],
)
